generateData.js 수정
johngrib/johngrib-jekyll-skeleton pull request #35
Opened 2021-04-22 01:50 UTC by yujong-lee

#33 에서 말씀드린대로 generateData.js를 수정했습니다.
수정 전후 코드가 동일하게 동작함을 확인하기 위해 테스트 코드도 작성하였습니다.
수정 전과 코드의 동작에 차이가 없기 때문에 #34 는 해결되지 않았습니다.

2021-04-22 01:52 UTC, yujong-lee commented
이제 보니 커밋을 조금 더 나누어서 할 걸 그랬네요.  양해 부탁드리겠습니다.

2021-04-22 13:00 UTC, johngrib commented
> 이제 보니 [8b2f011](https://github.com/johngrib/johngrib-jekyll-skeleton/commit/8b2f01135dd006faf69a25b93ea227acf408d62c) 커밋은 조금 더 나누어서 할 걸 그랬네요. 양해 부탁드리겠습니다.

이 PR을 머지하게 될 경우 `squash and merge`를 할 예정입니다. 그래서 괜찮습니다.

2021-04-22 13:07 UTC, johngrib requested changes
작업에서 yml 파일은 제외해 주세요.

2021-04-22 13:13 UTC, johngrib requested changes
fixture가 필요 이상으로 많습니다. 1~2개 정도로 줄이거나 테스트를 삭제하는 것이 좋겠습니다.

2021-04-22 13:13 UTC, johngrib commented on .babelrc
> +}
이 설정은 불필요합니다. PR에서 제외해주세요.

2021-04-22 13:17 UTC, johngrib reviewed
PR 타이틀을 명령형으로 수정해 주세요. `generateData.js 수정`에서 다음과 같이 바꾸는 것을 고려할 수 있겠습니다.

- `메타 데이터 생성기를 리팩토링하라`
- `generateData.js를 리팩토링하라`

2021-04-22 13:21 UTC, yujong-lee commented
.babelrc 파일을 삭제하고 테스트 코드와 테스트 데이터를 모두 삭제하였습니다.
PR 이름도 수정했습니다.

2021-04-22 13:29 UTC, yujong-lee commented on .babelrc
> +}
제외 했습니다.

2021-04-22 13:32 UTC, johngrib requested changes

2021-04-22 13:32 UTC, johngrib commented on generateData.js
> +}
파일 마지막에 개행 문자 하나를 추가해 주세요. (마지막엔 빈 줄 하나를 추가해 주시면 됩니다.) 그러면 github에서 보여주고 있는 다음 경고가 사라집니다.
![image](https://user-images.githubusercontent.com/1855714/115723020-84ab5e80-a3ba-11eb-93c2-29bb8118efed.png)

2021-04-22 13:42 UTC, yujong-lee commented on generateData.js
> +}
추가했습니다.

2021-04-22 14:43 UTC, johngrib commented on generateData.js
> +}
감사합니다!

2021-04-22 14:47 UTC, johngrib requested changes
중괄호 없는 `if`만 고쳐주시면 무리 없이 머지할 수 있겠습니다.

2021-04-22 14:47 UTC, johngrib commented on generateData.js
> +    if (!data.tag) return;
```suggestion
    if (!data.tag) {
        return;
    }
```

2021-04-22 14:47 UTC, johngrib commented on generateData.js
> +            if (err) return console.log(err);
```suggestion
            if (err) {
                return console.log(err);
            }
```

2021-04-22 14:47 UTC, johngrib commented on generateData.js
> +        if (err) return console.log(err);
```suggestion
        if (err) {
            return console.log(err);
        }
```

2021-04-22 14:47 UTC, johngrib commented on generateData.js
> +        if (err) return console.log(err);
```suggestion
        if (err) {
            return console.log(err);
        }
```

2021-04-22 14:47 UTC, johngrib commented on generateData.js
> +    if (info === null) return undefined;
```suggestion
    if (info === null) {
        return undefined;
    }
```

2021-04-22 14:47 UTC, johngrib commented on generateData.js
> +        if (result == null) return;
```suggestion
        if (result == null) {
            return;
        }
```

2021-04-22 14:47 UTC, johngrib commented on generateData.js
> +            if(testFileList && !testFileList.includes(fileName)) return;
```suggestion
            if(testFileList && !testFileList.includes(fileName)) {
                return;
            }
```

2021-04-22 23:37 UTC, yujong-lee commented
궁금한 것이 있습니다.

1. 중괄호 없이 if문을 쓰는 것은(그것이 짧다해도) 일반적으로 안티패턴으로 여겨지는 것인가요 아니면 그렇게 하지 않는 것이 이 래포지토리의 코딩스타일인가요?
2. 코드에 동등연산자(==)가 사용된 것이 몇 군데 있는데 이것을 일치연산자(===)로 바꾸는 것이 좋을까요?

2021-04-23 10:56 UTC, johngrib commented
> 궁금한 것이 있습니다.
> 
> 1. 중괄호 없이 if문을 쓰는 것은(그것이 짧다해도) 일반적으로 안티패턴으로 여겨지는 것인가요 아니면 그렇게 하지 않는 것이 이 래포지토리의 코딩스타일인가요?
> 2. 코드에 동등연산자(==)가 사용된 것이 몇 군데 있는데 이것을 일치연산자(===)로 바꾸는 것이 좋을까요?

1. 네. 네. 이에 대해서는 특별한 부연 설명이 필요하지 않다고 생각해요. 이야기가 나온 김에 이와 관련된 유명하고 재미있는 버그 이야기가 있습니다. Apple의 SSL/TLS 프로토콜에서 발견된 끔찍한 실수입니다. https://embeddedgurus.com/barr-code/2014/03/apples-gotofail-ssl-security-bug-was-easily-preventable/
2. 그것도 괜찮겠죠.

2021-04-23 10:56 UTC, merged

2021-04-23 10:57 UTC, johngrib commented
@yujong-lee 고생하셨습니다!